### ISSUE TITLE
TraceBackground compiled extension

### ISSUE THREAD

**Issue by davelab6** [schriftgestalt/Glyphs-Plugins#1]
Please include a compiled TraceBackground extension so its easy to use :)

**Comment by schriftgestalt** [comment]
There is a compiled plugin. The folder `TraceBackground` contains the source but next to it is the finished plugin.

**Comment by davelab6** [comment]
Should it have a file extension?

cc @mekkablue

**Comment by schriftgestalt** [comment]
Sorry, I mixed it up. That is a different plugin ;). I'll add it.

**Comment by schriftgestalt** [comment]
Just uploaded a new version. It includes a binary version.
